Layout/IndentationWidth:
    Width: 4

Layout/EndOfLine:
    EnforcedStyle: crlf

Style/FrozenStringLiteralComment:
    Enabled: false

Style/ClassVars:
    Enabled: false

Style/NumericLiterals:
    Enabled: false

Style/ConditionalAssignment:
    Enabled: false